  language: node_js
  node_js:
    - "0.10"
  env: NODE_ENV=test

  before_script:
    - mysql -e 'create database rfcx_api_travis;'
    - mysql -e 'grant all on rfcx_api_travis.* to "rfcx"@"localhost" identified by "password";'
